### ISSUE TITLE
How to bootstrap into an empty directory

### ISSUE THREAD

**Issue by lcnbr** [accelbread/flakelight-rust#2]
If I want to use this flake in an empty directory I cannot since I do not have a cargo.toml file, and no cargo to make it. I can just manually create the file but this seems unnecessary no?

**Comment by accelbread** [comment]
If, in that empty directory, you run `nix flake init -t github:accelbread/flakelight-rust` it will set up a starting project for you with a Cargo.toml and ready for use with `nix develop`.

Does that meet your needs?

**Comment by accelbread** [comment]
Added 5e2e3ed28f547e7fd76bc9126251505739586091 which enables using the devShell without a Cargo.toml present.
